require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.mini") -- devicons mock must precede icon consumers
require("plugins.treesj")
require("plugins.tiny-inline-diagnostic")
require("plugins.quicker")
require("plugins.zdiff")
require("plugins.fzf-lua")
require("plugins.lualine")
require("plugins.oil")
require("plugins.tiny-cmdline")
require("plugins.conform")
require("plugins.completion")
require("plugins.floaterminal")
