require("plugins.packs")
require("plugins.lsp")
require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.mini") -- devicons mock must precede icon consumers
require("plugins.misc")
require("plugins.fzf-lua")
require("plugins.oil")
require("plugins.tiny-cmdline")
require("plugins.completion")
require("plugins.floaterminal")
