vim.pack.add({
  { src = "https://github.com/nvim-mini/mini.nvim", version = "stable" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
  { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("1.*") },
  "https://github.com/rafamadriz/friendly-snippets",
  "https://github.com/rebelot/kanagawa.nvim",
  "https://github.com/kylechui/nvim-surround",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/wansmer/treesj",
  "https://github.com/rachartier/tiny-inline-diagnostic.nvim",
  "https://github.com/ibhagwan/fzf-lua",
  "https://github.com/rachartier/tiny-code-action.nvim",
  "https://github.com/nvim-lualine/lualine.nvim",
  "https://github.com/stevearc/oil.nvim",
  "https://github.com/malewicz1337/oil-git.nvim",
  "https://github.com/rachartier/tiny-cmdline.nvim",
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/b0o/SchemaStore.nvim",
  "https://github.com/artemave/workspace-diagnostics.nvim",
})
